return {
	[1] = {
		["id"] = 1,
		["labelName_t"] = "Cup",
	},
	[2] = {
		["id"] = 2,
		["labelName_t"] = "Arrow",
	},
	[3] = {
		["id"] = 3,
		["labelName_t"] = "Duck",
	},
	[4] = {
		["id"] = 4,
		["labelName_t"] = "Stone",
	},
	[5] = {
		["id"] = 5,
		["labelName_t"] = "SoundWaves",
	},
	[6] = {
		["id"] = 6,
		["labelName_t"] = "Paper",
	},
	[7] = {
		["id"] = 7,
		["labelName_t"] = "Pointer",
	},
	[8] = {
		["id"] = 8,
		["labelName_t"] = "Darts",
	},
	[9] = {
		["id"] = 9,
		["labelName_t"] = "Bullet",
	},
}